---
- hosts: localhost
  name: Personal Mac development environment

  vars_files:
    - local.config.yml

  roles:
    - role: macos
      tags: [macos]
    - role: git
      tags: [git]
    - role: dotfiles
      tags: [dotfiles]
    - role: homebrew
      tags: [homebrew]
    - role: sdkman
      tags: [sdkman]
    - role: jenv
      tags: [jenv]
    - role: certificates
      tags: [certificates]
