---
- name: 'Check mandatory Git configuration variables are defined'
  ansible.builtin.assert:
    that:
      - git_user_name
      - git_user_email

- name: "Set Git user name"
  community.general.git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global

- name: "Set Git user email"
  community.general.git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global

- name: "Set Git auto-converting CRLF"
  community.general.git_config:
    name: core.autocrlf
    value: "{{ git_autocrlf }}"
    scope: global

- name: "Set Git global .gitignore"
  community.general.git_config:
    name: core.excludesFile
    value: "{{ git_global_gitignore }}"
    scope: global

- name: "Set Git log alias"
  community.general.git_config:
    name: "alias.{{ item.name }}"
    value: "{{ item.command }}"
    scope: global
  with_items: "{{ git_aliases }}"

- name: 'Check mandatory Git signing configuration variables are defined'
  ansible.builtin.assert:
    that:
      - git_signing_key_id
      - git_signing_commit_default
      - git_signing_program
  when: git_signing_enabled

- name: "Set Git signing key ID"
  community.general.git_config:
    name: "user.signingkey"
    value: "{{ git_signing_key_id }}"
    scope: global
  when: git_signing_enabled

- name: "Set Git signing commit default"
  community.general.git_config:
    name: "commit.gpgsign"
    value: "{{ git_signing_commit_default }}"
    scope: global
  when: git_signing_enabled

- name: "Set Git signing program"
  community.general.git_config:
    name: "gpg.program"
    value: "{{ git_signing_program }}"
    scope: global
  when: git_signing_enabled

- name: "Unset Git signing key ID"
  community.general.git_config:
    name: "user.signingkey"
    scope: global
    state: absent
  when: not git_signing_enabled

- name: "Unset Git signing commit default"
  community.general.git_config:
    name: "commit.gpgsign"
    scope: global
    state: absent
  when: not git_signing_enabled

- name: "Unset Git signing program"
  community.general.git_config:
    name: "gpg.program"
    scope: global
    state: absent
  when: not git_signing_enabled
